# Copyright (c) 1990,1991,1992 Chris and John Downey
#***
#
# program name:
#	xvi
# function:
#	PD version of UNIX "vi" editor, with extensions.
# module name:
#	makefile.nt
# module function:
#	Makefile for Windows NT and Microsoft C/C++
# history:
#	STEVIE - ST Editor for VI Enthusiasts, Version 3.10
#	Originally by Tim Thompson (twitch!tjt)
#	Extensive modifications by Tony Andrews (onecom!wldrdg!tony)
#	Heavily modified by Chris & John Downey
#***



#!include <ntwin32.mak>

#
# Name of this file.
#
THISFILE=	makefile.nt

XVIOBJ=		defscr.obj \
		alloc.obj ascii.obj buffers.obj cmdline.obj cursor.obj \
		edit.obj ex_cmds1.obj ex_cmds2.obj events.obj fileio.obj \
		find.obj flexbuf.obj map.obj mark.obj misccmds.obj \
		mouse.obj movement.obj \
		normal.obj param.obj pipe.obj preserve.obj ptrfunc.obj \
		regexp.obj screen.obj search.obj startup.obj status.obj \
		tags.obj undo.obj version.obj windows.obj \
		yankput.obj nt.obj

all:		xvi.exe

xvi.exe:	$(XVIOBJ)
		cl  /Fexvi.exe  $(XVIOBJ) 

.c.obj:
		cl /c -DWIN32 $(cvars) $(cdebug) $*.c

clean:
		del *.obj *.exe
